# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_article_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='tid',
        ),
    ]
