# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_talk_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
