# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170726_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discount',
            field=models.TextField(null=True),
        ),
    ]
