# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('discount', models.TextField(null=True)),
            ],
        ),
    ]
